 
name: Acces to the building

on: [workflow_dispatch]

jobs: 
  security-access:
    runs-on: ubuntu-latest

    steps: 
      - name: The agent arrives to the building
        run: |
          echo "Agent ${{github.actor}}"
          echo "==="
          echo "Search for the legion files"
          ls -la
          echo "==="
          echo "X what's happening. Any file is found."

      - name: "Brainiac remove the accces to the vault"
        uses: actions/checkout@v4

      - name: "Now it's fine we can access to the plans"
        run: |
          echo "Search for the secret files of the Legion"
          ls -la
          echo "Works!!"
          echo "Secret Plans:"
          ls planes/
          echo "Villains:"
          ls miembros/
          echo "Inteligence:"
          ls inteligencia/
