name: Comunicator of the legion

on:
  workflow_dispatch:
    inputs:
      villain:
        description: "What villain send the message?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Joker
          - Mystyque
          - Brainiac
          - Doom

      message:
        description: "Message for the council"
        required: true
        default: "The mission was an exit"

      priority:
        description: "Priority level"
        required: true
        type: choice
        options:
          - Normal
          - High
          - Critical

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Install the transmissor of the company
        run: sudo apt-get install -y cowsay

      - name: Print inputs
        run: |
          echo "===================================="
          echo "      Transmission on course        "
          echo "===================================="
          echo ""
          echo "From: ${{ inputs.villain }}"
          echo ""
          echo "Date: $(date -u +"%d/%m/%Y - %H:%M UTC")"
          echo "---------Message--------"
          cowsay -f eyes "${{ inputs.message }}"
          echo ""
          echo "------ ${{ inputs.villain}}-------"
          echo "..."

